# Generated by Django 5.2.17 on 2026-09-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assign_super_admin_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permission',
            table='permissions',
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='rolepermission',
            table='rolepermissions',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
