# Generated by Django 5.2.17 on 2026-09-07 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_permission_table_alter_role_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'provinces',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='core.district')),
            ],
            options={
                'db_table': 'municipalities',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.province'),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo_url', models.URLField(blank=True)),
                ('brand_colors', models.JSONField(blank=True, default=dict)),
                ('sector', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=10)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='core.municipality')),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('student_id_card', 'Student ID Card'), ('cv_resume', 'CV / Resume'), ('certificate', 'Certificate'), ('recommendation_letter', 'Recommendation Letter')], max_length=30)),
                ('file_url', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_documents',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('available_sikka', models.IntegerField(default=0)),
                ('total_earned_sikka', models.IntegerField(default=0)),
                ('used_sikka', models.IntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='core.district')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='core.grade')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='core.province')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='core.school')),
                ('student_id_card_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='core.verificationdocument')),
            ],
            options={
                'db_table': 'student_profiles',
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='instructor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('qualification', models.CharField(max_length=255)),
                ('subject_expertise', models.TextField()),
                ('experience_years', models.DecimalField(decimal_places=2, max_digits=5)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructor_profiles', to='core.school')),
                ('cv_resume_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_profiles', to='core.verificationdocument')),
            ],
            options={
                'db_table': 'instructor_profiles',
            },
        ),
        migrations.AddConstraint(
            model_name='municipality',
            constraint=models.UniqueConstraint(fields=('district', 'name'), name='unique_municipality_per_district'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('province', 'name'), name='unique_district_per_province'),
        ),
    ]
