# Generated by Django 5.2.17 on 2026-09-07 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_district_grade_province_municipality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructor_profiles', to='core.district'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructor_profiles', to='core.province'),
        ),
    ]
