# Generated by Django 5.2.17 on 2026-09-07 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_instructorprofile_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructor_profiles', to='core.municipality'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='core.municipality'),
        ),
    ]
