# Generated by Django 5.2.17 on 2026-09-09 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('core', '0011_topic_lesson'),
	]

	operations = [
		migrations.CreateModel(
			name='PasswordResetOTP',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('otp_hash', models.CharField(max_length=128)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('expires_at', models.DateTimeField()),
				('is_used', models.BooleanField(default=False)),
				('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL)),
			],
			options={
				'db_table': 'password_reset_otps',
				'ordering': ['-created_at'],
			},
		),
	]