# Generated by Django 5.2.17 on 2026-09-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_question_questionoption_quiz_question_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
