# Generated by Django 5.2.17 on 2026-09-18 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningStreak',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='learning_streak', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'learning_streaks',
            },
        ),
        migrations.CreateModel(
            name='StreakSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_period_days', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'streak_settings',
            },
        ),
        migrations.CreateModel(
            name='StreakHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'streak_history',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='unique_streak_day_per_student')],
            },
        ),
    ]
