# Generated by Django 5.2.17 on 2026-09-21 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_question_questionoption_quiz_question_quiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_course_requires_quiz_pass', models.BooleanField(default=True)),
                ('academic_grade_min_completion_percentage', models.PositiveSmallIntegerField(default=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'certificate_criteria',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('course', 'Course Completion'), ('grade', 'Grade Completion')], max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.course')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificates',
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='unique_course_certificate_per_student'), models.UniqueConstraint(fields=('student', 'grade'), name='unique_grade_certificate_per_student')],
            },
        ),
    ]
