# Generated by Django 5.2.17 on 2026-09-21 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_certificatecriteria_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True)),
                ('criteria_type', models.CharField(choices=[('quiz_perfect_score', 'Perfect Quiz Score'), ('streak_milestone', 'Streak Milestone'), ('course_completion_count', 'Number of Courses Completed')], max_length=30)),
                ('criteria_value', models.PositiveIntegerField(help_text='e.g. streak days needed, or number of courses')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'badges',
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='core.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_badges',
                'constraints': [models.UniqueConstraint(fields=('student', 'badge'), name='unique_badge_per_student')],
            },
        ),
    ]
