# Generated by Django 5.2.17 on 2026-09-21 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
              ('core', '0024_challenge_challengeparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shorts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shorts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.short')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'short_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.short')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'short_likes',
                'constraints': [models.UniqueConstraint(fields=('student', 'short'), name='unique_short_like_per_student')],
            },
        ),
        migrations.CreateModel(
            name='ShortView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.short')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'short_views',
                'constraints': [models.UniqueConstraint(fields=('student', 'short'), name='unique_short_view_per_student')],
            },
        ),
    ]
