# Generated by Django 5.2.17 on 2026-09-22 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_short_shortcomment_shortlike_shortview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='core.district'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='core.grade'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='core.province'),
        ),
    ]
