# Generated by Django 5.2.17 on 2026-09-22 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_short_shortcomment_shortlike_shortview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('practice_questions', 'Practice Questions'), ('crossword', 'Crossword'), ('challenge', 'Challenge')], max_length=30)),
                ('topic', models.CharField(max_length=255)),
                ('learning_context', models.TextField(blank=True)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('generated_content', models.JSONField()),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_ai_activities', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
