# Generated by Django 5.2.17 on 2026-09-22 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
              ('core', '0027_ebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('course_update', 'Course Update'), ('assessment_result', 'Assessment Result'), ('payment', 'Payment Confirmation'), ('certificate', 'Certificate'), ('challenge', 'Challenge'), ('system', 'System')], default='system', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_type', models.CharField(blank=True, max_length=50)),
                ('related_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx')],
            },
        ),
    ]
