# Generated by Django 5.2.17 on 2026-09-22 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
                ('core', '0029_aiactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAuthorityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_authority_profiles', to='core.municipality')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_authority_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'local_authority_profiles',
            },
        ),
    ]
