# Generated by Django 5.2.17 on 2026-10-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='experience_years',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='subject_expertise',
            field=models.TextField(blank=True, default=''),
        ),
    ]
