# Generated by Django 5.2.17 on 2026-09-28 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_instructorprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('points_required', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited stock.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rewards',
                'ordering': ['points_required', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='event_type',
            field=models.CharField(choices=[('quiz_correct_answer', 'Quiz Correct Answer'), ('quiz_first_time_correct', 'Quiz First-Time Correct'), ('quiz_completion', 'Quiz Completion'), ('course_completion', 'Course Completion'), ('challenge_completion', 'Challenge Completion'), ('manual_adjustment', 'Manual Adjustment'), ('reward_redemption', 'Reward Redemption')], max_length=50),
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='redemption', to='core.pointtransaction')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='core.reward')),
            ],
            options={
                'db_table': 'redemptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
