# Generated by Django 5.2.17 on 2026-10-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_instructor_signup_email_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_interests',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='onboarding_flow_version',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Legacy'), (2, 'Learning interests')], default=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='learning_interests',
            field=models.ManyToManyField(blank=True, related_name='student_profiles', to='core.learninginterest'),
        ),
    ]
