# Generated by Django 5.2.17 on 2026-10-06 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='core.short')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'short_bookmarks',
                'constraints': [models.UniqueConstraint(fields=('student', 'short'), name='unique_short_bookmark_per_student')],
            },
        ),
    ]
