# Generated by Django 5.2.17 on 2026-10-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_shortbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
