# Generated by Django 5.2.17 on 2026-10-08 06:52

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_password_reset_otp_failed_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('cover_image', models.ImageField(blank=True, upload_to=core.models.event_image_path)),
                ('host_role', models.CharField(blank=True, max_length=150)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('format', models.CharField(choices=[('in_person', 'In person'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='in_person', max_length=20)),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.district')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_events', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.municipality')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.province')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['start_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='core.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_bookmarks',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('waitlisted', 'Waitlisted')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_registrations',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_published', 'end_at'], name='events_is_publ_1d450c_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gte', models.F('start_at'))), name='event_valid_schedule'),
        ),
        migrations.AddConstraint(
            model_name='eventbookmark',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_registration'),
        ),
    ]
