# Generated by Django 5.2.17 on 2026-10-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
