"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-8qtkd&ixe31xqfku2%mfq0_u55ny=o#9cupcr#ks4!bm2grt56'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config(
    'DEBUG',
    default=True,
    cast=bool
)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1',
    cast=Csv()
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'corsheaders',

    'core',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'config.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# Database
# Defaults to SQLite for local development.
# Set DB_ENGINE=mysql in .env to use MySQL.

if config('DB_ENGINE', default='sqlite') == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config(
                'DB_NAME',
                default='skillsikka'
            ),
            'USER': config(
                'DB_USER',
                default='root'
            ),
            'PASSWORD': config(
                'DB_PASSWORD',
                default='root'
            ),
            'HOST': config(
                'DB_HOST',
                default='127.0.0.1'
            ),
            'PORT': config(
                'DB_PORT',
                default='3307'
            ),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]


# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'


STORAGES = {
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.'
            'CompressedManifestStaticFilesStorage'
        ),
    },
}


if config('USE_S3', default=False, cast=bool):
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')

    AWS_S3_REGION_NAME = config(
        'AWS_S3_REGION_NAME',
        default='ap-south-1'
    )

    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False

    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage'
    }

else:

    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    STORAGES['default'] = {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    }


# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom User Model

AUTH_USER_MODEL = 'core.User'


# Django web authentication redirects

LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login'


# Django REST Framework / JWT

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'core.authentication.EmailVerifiedJWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': (
        'drf_spectacular.openapi.AutoSchema'
    ),
}


# OpenAPI / Swagger schema

SPECTACULAR_SETTINGS = {
    'TITLE': 'SkillSikka API',
    'DESCRIPTION': 'SkillSikka backend REST API',
    'VERSION': 'v1',
}


# CORS / CSRF

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='',
    cast=Csv()
)

CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='',
    cast=Csv()
)


# HTTPS / Production security

ENABLE_HTTPS = config(
    'ENABLE_HTTPS',
    default=False,
    cast=bool
)

if not DEBUG and ENABLE_HTTPS:
    SECURE_PROXY_SSL_HEADER = (
        'HTTP_X_FORWARDED_PROTO',
        'https'
    )

    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Email
# With EMAIL_HOST set, mail goes out over SMTP (e.g. Mailtrap); without it,
# emails such as OTPs are printed in the Django terminal.

EMAIL_HOST = config('EMAIL_HOST', default='')

if EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
    EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL',
    default='noreply@skillsikka.com'
)


# Payments (Khalti, eSewa)
# PAYMENT_MODE=sandbox uses the gateways' test environments; the eSewa test
# merchant works out of the box, Khalti needs a sandbox secret key from
# https://test-admin.khalti.com. PAYMENT_MODE=live needs real merchant keys.

PAYMENT_MODE = config('PAYMENT_MODE', default='sandbox')
_LIVE_PAYMENTS = PAYMENT_MODE == 'live'

KHALTI_SECRET_KEY = config('KHALTI_SECRET_KEY', default='')
KHALTI_BASE_URL = config(
    'KHALTI_BASE_URL',
    default='https://khalti.com/api/v2/' if _LIVE_PAYMENTS else 'https://dev.khalti.com/api/v2/',
)

# Empty values fall back to eSewa's public test merchant in sandbox mode.
ESEWA_PRODUCT_CODE = config('ESEWA_PRODUCT_CODE', default='') or ('' if _LIVE_PAYMENTS else 'EPAYTEST')
ESEWA_SECRET_KEY = config('ESEWA_SECRET_KEY', default='') or ('' if _LIVE_PAYMENTS else '8gBm/:&EnhH.1/q')
ESEWA_FORM_URL = config(
    'ESEWA_FORM_URL',
    default='https://epay.esewa.com.np/api/epay/main/v2/form' if _LIVE_PAYMENTS
    else 'https://rc-epay.esewa.com.np/api/epay/main/v2/form',
)
ESEWA_STATUS_URL = config(
    'ESEWA_STATUS_URL',
    default='https://esewa.com.np/api/epay/transaction/status/' if _LIVE_PAYMENTS
    else 'https://rc.esewa.com.np/api/epay/transaction/status/',
)

# Optional app deep link to send the user to after paying, e.g.
# skillsikka://payment-complete. Empty: the server shows a result page.
PAYMENT_APP_RETURN_URL = config('PAYMENT_APP_RETURN_URL', default='')

# Gemini AI
# Gemini AI
GEMINI_API_KEY = config(
    'GEMINI_API_KEY',
    default=''
)
# Simple JWT token lifetime configuration

from datetime import timedelta

SIMPLE_JWT = {
    'USER_AUTHENTICATION_RULE': 'core.authentication.email_authentication_rule',
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# API throttling configuration

REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = (
    'rest_framework.throttling.AnonRateThrottle',
    'rest_framework.throttling.UserRateThrottle',
)

REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
    'anon': '20/minute',
    'user': '120/minute',
}
